# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: local
  hooks:
  - id: black
    name: Python format (black)
    entry: black
    language: system
    types: [python]
  - id: isort
    name: Python format (isort)
    entry: isort
    language: system
    types: [python]
  - id: mypy
    pass_filenames: false
    name: Python typecheck (mypy)
    entry: make mypy
    language: system
    types: [python]
  - id: flake8
    name: Python lint (flake8)
    entry: flake8
    language: system
    types: [python]
  - id: pytest-check
    name: Testing (pytest)
    entry: pytest
    language: system
    pass_filenames: false
    always_run: true
